name: Update courses into the database

on:
  push:
    branches: [ "main" ]
    paths: [ "courses/**" ]

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          FORMAT: json
      - name: Send POST request
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          API_URL: "https://breadboard.up.railway.app/courses"
        run: |
          curl -H "Authorization: Bearer $JWT_SECRET" \
          -H "Content-Type: application/json" \
          -d '${{ env.GIT_DIFF }}' \
          "$API_URL" \
          -v
